
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/user1/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/remote-cli/"
      - "/home/user1/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/d/VScode/Microsoft VS Code/"
      - "/mnt/d/app/timea/product/11.2.0/client_1/bin/"
      - "/mnt/c/Program Files/Java/jdk-17.0.5/bin/"
      - "/mnt/d/Maven/apache-maven-3.9.9/bin/"
      - "/mnt/d/\u865a\u62df\u673a/bin/"
      - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath/"
      - "/mnt/c/Windows/system32/"
      - "/mnt/c/Windows/"
      - "/mnt/c/Windows/System32/Wbem/"
      - "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/Windows/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/Tencent/WeChat/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files/nodejs/"
      - "/mnt/c/Program Files/Docker/Docker/resources/bin/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/Calibre2/"
      - "/mnt/c/Users/timea/AppData/Local/Programs/Python/Python310/Scripts/"
      - "/mnt/c/Users/timea/AppData/Local/Programs/Python/Python310/"
      - "/mnt/c/Program Files/MySQL/MySQL Shell 8.0/bin/"
      - "/mnt/c/mingw64/bin/"
      - "/mnt/c/Users/timea/AppData/Roaming/npm/"
      - "/mnt/c/Users/timea/AppData/Roaming/cabal/bin/"
      - "/mnt/c/tools/ghc-9.8.2/bin/"
      - "/mnt/d/IDEA/IntelliJ IDEA 2024.3.5/bin/"
      - "/mnt/d/VScode/Microsoft VS Code/bin/"
      - "/snap/bin/"
      - "/home/user/.local/bin/"
    searched_directories:
      - "/home/user1/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/remote-cli/uname"
      - "/home/user1/.local/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/user1/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/remote-cli"
        - "/home/user1/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/d/VScode/Microsoft VS Code"
        - "/mnt/d/app/timea/product/11.2.0/client_1/bin"
        - "/mnt/c/Program Files/Java/jdk-17.0.5/bin"
        - "/mnt/d/Maven/apache-maven-3.9.9/bin"
        - "/mnt/d/\u865a\u62df\u673a/bin/"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath"
        - "/mnt/c/Windows/system32"
        - "/mnt/c/Windows"
        - "/mnt/c/Windows/System32/Wbem"
        - "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/Windows/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common"
        - "/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/Tencent/WeChat"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files/nodejs/"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/Program Files/Calibre2/"
        - "/mnt/c/Users/timea/AppData/Local/Programs/Python/Python310/Scripts/"
        - "/mnt/c/Users/timea/AppData/Local/Programs/Python/Python310/"
        - "/mnt/c/Program Files/MySQL/MySQL Shell 8.0/bin/"
        - "/mnt/c/mingw64/bin"
        - "/mnt/c/Users/timea/AppData/Roaming/npm"
        - "/mnt/c/Users/timea/AppData/Roaming/cabal/bin"
        - "/mnt/c/tools/ghc-9.8.2/bin"
        - "/mnt/d/IDEA/IntelliJ IDEA 2024.3.5/bin"
        - "/mnt/d/VScode/Microsoft VS Code/bin"
        - "/snap/bin"
        - "/home/user/.local/bin"
        - "/home/user/.local/bin"
        - "/home/user/.local/bin"
        - "/home/user/.local/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.4/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.146.1-microsoft-standard-WSL2 - x86_64
...
