include("/usr/share/cmake-4.4/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[matching_tests]==]
  TEST_EXECUTABLE [==[/home/user1/low-latency-trading-system/build-sanitize/matching_tests]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/home/user1/low-latency-trading-system/build-sanitize]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[matching_tests_TESTS]==]
  CTEST_FILE [==[/home/user1/low-latency-trading-system/build-sanitize/matching_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/home/user1/low-latency-trading-system/build-sanitize]==]
)
