if(EXISTS "/home/user1/low-latency-trading-system/build-sanitize/matching_tests_e3b0c442_tests.cmake")
  include("/home/user1/low-latency-trading-system/build-sanitize/matching_tests_e3b0c442_tests.cmake")
else()
  add_test(matching_tests_NOT_BUILT matching_tests_NOT_BUILT)
endif()
